
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html>
      <body>
        {children}
        <header>
          <nav>
            <Link href="/pages/studio">studio</Link>
            <Link href="/pages/lab">lab</Link>
            <Link href="/pages/research">research</Link>
            <Link href="/pages/people">people</Link>
          </nav>
        </header>
      </body>
    </html>
  )
}
