import './globals.css'
import '/public/fonts/font.css'
import { Space_Grotesk } from 'next/font/google'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const space_grotesk=Space_Grotesk({
  weight:['300','400','500','700'],//light , regular, medium, bold
  subsets: ['latin'],
})

export default function RootLayout({ children }) {

  return (
    <html>
      <body className={space_grotesk.className}>
        {children}
        <header>
          <nav style={{fontWeight:'400'}}>
            <Link href="/">about</Link>
            <Link href="/pages/studio">work</Link>
            <Link href="/pages/research">service</Link>
            <Link href="/pages/people">contact</Link>
          </nav>
        </header>
      </body>
    </html>
  )
}
